#pragma once

#include <luisa/dsl/polymorphic.h>
#include "newtype/render/SurfaceData.h"
#include "newtype/render/MaterialPool.h"

namespace newtype::render {

using namespace luisa;
using namespace luisa::compute;

//==============================================================================
// SurfaceResolver — Virtual base for per-type surface resolution
//==============================================================================

/// Base class for material-type-specific surface parameter transformation.
/// Each material type (built-in or custom) registers an implementation
/// with a Polymorphic<SurfaceResolver>. The resolve() method is called
/// during device.compile() (AST build time) and emits DSL nodes.
///
/// Default resolve() is a no-op (identity transform). Built-in types
/// inherit this. Custom types override to apply procedural effects.
class SurfaceResolver {
public:
    virtual ~SurfaceResolver() noexcept = default;

    /// Transform surface data for this material type.
    /// Called inside the $switch dispatch generated by Polymorphic::dispatch().
    ///
    /// @param s            Surface data after texture sampling (mutable).
    ///                     UV is in s.uv — read it from there.
    /// @param material     Raw material data from GPU buffer
    /// @param screen_uv    Screen-space position [0,1]
    /// @param wo           Outgoing view direction
    /// @param time         Time parameter (frame_count as float)
    /// @param tex_bindless Texture bindless array
    /// @param screen_w     Screen width
    /// @param screen_h     Screen height
    virtual void resolve(
        SurfaceData& s,
        const Var<MaterialData>& material,
        Float2 screen_uv, Float3 wo, Float time,
        const BindlessVar& tex_bindless,
        UInt screen_w, UInt screen_h) const noexcept {
        // Identity: do nothing
    }
};

//==============================================================================
// Concrete Implementations
//==============================================================================

/// Identity resolver for built-in material types (0-13).
/// Inherits the default no-op resolve().
class IdentitySurfaceResolver : public SurfaceResolver {};

/// Wraps a lambda/function into a SurfaceResolver for custom materials.
/// F must be callable with the SurfaceResolveFn signature:
///   SurfaceData(SurfaceData, Var<MaterialData>, Float2, Float3, Float,
///               const BindlessVar&, UInt, UInt)
/// (positional args after material: screen_uv, wo, time, tex_bindless, w, h.
///  UV is read from s.uv inside the callable.)
template<typename F>
class CustomSurfaceResolver : public SurfaceResolver {
    F _fn;
public:
    explicit CustomSurfaceResolver(F fn) : _fn(std::move(fn)) {}

    void resolve(
        SurfaceData& s,
        const Var<MaterialData>& material,
        Float2 screen_uv, Float3 wo, Float time,
        const BindlessVar& tex_bindless,
        UInt screen_w, UInt screen_h) const noexcept override {
        s = _fn(s, material, screen_uv, wo, time, tex_bindless, screen_w, screen_h);
    }
};

//==============================================================================
// Type Aliases
//==============================================================================

/// Polymorphic container type for surface resolvers.
using SurfaceResolverPoly = Polymorphic<SurfaceResolver>;

} // namespace newtype::render
